# Generated by Django 3.0.8 on 2020-09-15 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20200915_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('TS', 'T-Shirt'), ('SW', 'Sport Wear'), ('OW', 'OutWear')], max_length=2),
        ),
    ]
