# Generated by Django 3.0.8 on 2020-09-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20200915_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='tags',
            new_name='tag',
        ),
    ]
